[pytest]
asyncio_mode = auto
testpaths = tests_asi tests
log_cli = true
log_cli_level = INFO
python_classes = Test* AsiTester
filterwarnings =
    ignore:cannot collect test class 'TestStatus':pytest.PytestCollectionWarning
